sources:
  "1.9.1":
    source_archive:
      url: "https://github.com/google/benchmark/archive/refs/tags/v1.9.1.tar.gz"
      sha256: "32131c08ee31eeff2c8968d7e874f3cb648034377dfc32a4c377fa8796d84981"
      archive_type: "tar.gz"
      strip_prefix: "benchmark-1.9.1"
build:
  cmake_options:
    BUILD_SHARED_LIBS: "ON"
    BENCHMARK_ENABLE_TESTING: "OFF"
    BENCHMARK_ENABLE_GTEST_TESTS: "OFF"
    BENCHMARK_ENABLE_INSTALL: "ON"
    CMAKE_DEBUG_POSTFIX: "_d"
