sources:
  0.20.1:
    url: https://raw.githubusercontent.com/yhirose/cpp-httplib/v0.20.1/httplib.h
    sha256: 7d3f813d05dad23b9c66eb6d9c1ff3d66f6acfaf6e5900ce960f7990e78079ea
    target_path: include/httplib.h
