sources:
  4.11.0:
    url: https://github.com/opencv/opencv/archive/refs/tags/4.11.0.tar.gz
    sha256: 9a7c11f924eff5f8d8070e297b322ee68b9227e003fd600d4b8122198091665f
    archive_type: tar.gz
    strip_prefix: opencv-4.11.0
build:
  opencv:
    cmake_options:
      BUILD_SHARED_LIBS: 'ON'
      BUILD_opencv_world: 'ON'
      BUILD_TESTS: 'OFF'
      BUILD_PERF_TESTS: 'OFF'
      BUILD_EXAMPLES: 'OFF'
      BUILD_ANDROID_EXAMPLES: 'OFF'
      BUILD_ANDROID_PROJECTS: 'OFF'
      INSTALL_ANDROID_EXAMPLES: 'OFF'
      BUILD_opencv_apps: 'OFF'
      BUILD_JAVA: 'OFF'
      BUILD_WITH_DEBUG_INFO: 'OFF'
      WITH_FFMPEG: 'OFF'
      WITH_GSTREAMER: 'OFF'
      WITH_OPENCL: 'OFF'
      WITH_OPENCLAMDBLAS: 'OFF'
      WITH_OPENCLAMDFFT: 'OFF'
      WITH_OPENCL_D3D11_NV: 'OFF'
      WITH_CUDA: 'OFF'
      WITH_IPP: 'OFF'
      WITH_JPEG: 'OFF'
      WITH_TIFF: 'OFF'
      WITH_WEBP: 'OFF'
      WITH_OPENEXR: 'OFF'
      WITH_OPENJPEG: 'OFF'
      WITH_JASPER: 'OFF'
      WITH_PNG: 'ON'
      BUILD_PNG: 'ON'
      OPENCV_DNN_CUDA: 'OFF'
      OPENCV_DNN_OPENCL: 'OFF'
      OPENCV_DNN_TFLITE: 'OFF'
      OPENCV_ENABLE_ALLOCATOR_STATS: 'OFF'
      OPENCV_TRACE: 'OFF'
      OPENCV_BIN_INSTALL_PATH: bin
      OPENCV_LIB_INSTALL_PATH: lib
      OPENCV_INCLUDE_INSTALL_PATH: include
      OPENCV_CONFIG_INSTALL_PATH: lib/cmake/opencv4
    cmake_options_by_config:
      release:
        BUILD_LIST: core,imgproc,imgcodecs
        BUILD_opencv_dnn: 'OFF'
        BUILD_opencv_highgui: 'OFF'
        BUILD_opencv_videoio: 'OFF'
        ENABLE_LTO: 'ON'
        CMAKE_INTERPROCEDURAL_OPTIMIZATION: 'ON'
      debug:
        BUILD_LIST: core,imgproc,imgcodecs,dnn,highgui
        BUILD_opencv_highgui: 'ON'
        BUILD_opencv_videoio: 'OFF'
        WITH_WIN32UI: 'ON'
        ENABLE_LTO: 'OFF'
  opencv_dnn:
    cmake_options:
      BUILD_SHARED_LIBS: 'ON'
      BUILD_opencv_world: 'ON'
      BUILD_LIST: core,imgproc,imgcodecs,dnn
      BUILD_opencv_dnn: 'ON'
      BUILD_opencv_highgui: 'OFF'
      BUILD_opencv_videoio: 'OFF'
      BUILD_TESTS: 'OFF'
      BUILD_PERF_TESTS: 'OFF'
      BUILD_EXAMPLES: 'OFF'
      BUILD_ANDROID_EXAMPLES: 'OFF'
      BUILD_ANDROID_PROJECTS: 'OFF'
      INSTALL_ANDROID_EXAMPLES: 'OFF'
      BUILD_opencv_apps: 'OFF'
      BUILD_JAVA: 'OFF'
      BUILD_WITH_DEBUG_INFO: 'OFF'
      WITH_FFMPEG: 'OFF'
      WITH_GSTREAMER: 'OFF'
      WITH_OPENCL: 'OFF'
      WITH_OPENCLAMDBLAS: 'OFF'
      WITH_OPENCLAMDFFT: 'OFF'
      WITH_OPENCL_D3D11_NV: 'OFF'
      WITH_CUDA: 'OFF'
      WITH_IPP: 'OFF'
      WITH_JPEG: 'OFF'
      WITH_TIFF: 'OFF'
      WITH_WEBP: 'OFF'
      WITH_OPENEXR: 'OFF'
      WITH_OPENJPEG: 'OFF'
      WITH_JASPER: 'OFF'
      WITH_PNG: 'ON'
      BUILD_PNG: 'ON'
      OPENCV_DNN_CUDA: 'OFF'
      OPENCV_DNN_OPENCL: 'OFF'
      OPENCV_DNN_TFLITE: 'OFF'
      OPENCV_ENABLE_ALLOCATOR_STATS: 'OFF'
      OPENCV_TRACE: 'OFF'
      ENABLE_LTO: 'ON'
      CMAKE_INTERPROCEDURAL_OPTIMIZATION: 'ON'
      OPENCV_BIN_INSTALL_PATH: bin
      OPENCV_LIB_INSTALL_PATH: lib
      OPENCV_INCLUDE_INSTALL_PATH: include
      OPENCV_CONFIG_INSTALL_PATH: lib/cmake/opencv4
