sources:
  "4.13.0":
    url: "https://github.com/opencv/opencv/archive/refs/tags/4.13.0.tar.gz"
    sha256: "1d40ca017ea51c533cf9fd5cbde5b5fe7ae248291ddf2af99d4c17cf8e13017d"
    archive_type: "tar.gz"
    strip_prefix: "opencv-4.13.0"
build:
  opencv:
    cmake_options:
      BUILD_SHARED_LIBS: "ON"
      BUILD_opencv_world: "ON"
      BUILD_TESTS: "OFF"
      BUILD_PERF_TESTS: "OFF"
      BUILD_EXAMPLES: "OFF"
      BUILD_ANDROID_EXAMPLES: "OFF"
      BUILD_ANDROID_PROJECTS: "OFF"
      INSTALL_ANDROID_EXAMPLES: "OFF"
      BUILD_opencv_apps: "OFF"
      BUILD_opencv_gapi: "OFF"
      BUILD_JAVA: "OFF"
      BUILD_WITH_DEBUG_INFO: "OFF"
      WITH_FFMPEG: "OFF"
      WITH_GSTREAMER: "OFF"
      WITH_OPENCL: "OFF"
      WITH_OPENCLAMDBLAS: "OFF"
      WITH_OPENCLAMDFFT: "OFF"
      WITH_OPENCL_D3D11_NV: "OFF"
      WITH_CUDA: "OFF"
      WITH_IPP: "OFF"
      WITH_ITT: "OFF"
      WITH_ADE: "OFF"
      BUILD_WITH_STATIC_CRT: "OFF"
      WITH_JPEG: "OFF"
      WITH_TIFF: "OFF"
      WITH_WEBP: "OFF"
      WITH_OPENEXR: "OFF"
      WITH_OPENJPEG: "OFF"
      WITH_JASPER: "OFF"
      WITH_PNG: "ON"
      BUILD_PNG: "ON"
      OPENCV_DNN_CUDA: "OFF"
      OPENCV_DNN_OPENCL: "OFF"
      OPENCV_DNN_TFLITE: "OFF"
      OPENCV_ENABLE_ALLOCATOR_STATS: "OFF"
      OPENCV_TRACE: "OFF"
      OPENCV_BIN_INSTALL_PATH: "bin"
      OPENCV_LIB_INSTALL_PATH: "lib"
      OPENCV_INCLUDE_INSTALL_PATH: "include"
      OPENCV_CONFIG_INSTALL_PATH: "lib/cmake/opencv4"
    cmake_options_by_config:
      release:
        BUILD_LIST: "core,imgproc,imgcodecs"
        BUILD_opencv_dnn: "OFF"
        BUILD_PROTOBUF: "OFF"
        WITH_PROTOBUF: "OFF"
        BUILD_opencv_highgui: "OFF"
        BUILD_opencv_videoio: "OFF"
        ENABLE_LTO: "ON"
        CMAKE_INTERPROCEDURAL_OPTIMIZATION: "ON"
      debug:
        BUILD_LIST: "core,imgproc,imgcodecs,dnn,highgui"
        BUILD_opencv_highgui: "ON"
        BUILD_opencv_videoio: "OFF"
        WITH_WIN32UI: "ON"
        ENABLE_LTO: "OFF"
  opencv_dnn:
    cmake_options:
      BUILD_SHARED_LIBS: "ON"
      BUILD_opencv_world: "ON"
      BUILD_LIST: "core,imgproc,imgcodecs,dnn"
      BUILD_opencv_dnn: "ON"
      BUILD_opencv_highgui: "OFF"
      BUILD_opencv_videoio: "OFF"
      BUILD_TESTS: "OFF"
      BUILD_PERF_TESTS: "OFF"
      BUILD_EXAMPLES: "OFF"
      BUILD_ANDROID_EXAMPLES: "OFF"
      BUILD_ANDROID_PROJECTS: "OFF"
      INSTALL_ANDROID_EXAMPLES: "OFF"
      BUILD_opencv_apps: "OFF"
      BUILD_opencv_gapi: "OFF"
      BUILD_JAVA: "OFF"
      BUILD_WITH_DEBUG_INFO: "OFF"
      WITH_FFMPEG: "OFF"
      WITH_GSTREAMER: "OFF"
      WITH_OPENCL: "OFF"
      WITH_OPENCLAMDBLAS: "OFF"
      WITH_OPENCLAMDFFT: "OFF"
      WITH_OPENCL_D3D11_NV: "OFF"
      WITH_CUDA: "OFF"
      WITH_IPP: "OFF"
      WITH_ITT: "OFF"
      WITH_ADE: "OFF"
      BUILD_WITH_STATIC_CRT: "OFF"
      WITH_JPEG: "OFF"
      WITH_TIFF: "OFF"
      WITH_WEBP: "OFF"
      WITH_OPENEXR: "OFF"
      WITH_OPENJPEG: "OFF"
      WITH_JASPER: "OFF"
      WITH_PNG: "ON"
      BUILD_PNG: "ON"
      OPENCV_DNN_CUDA: "OFF"
      OPENCV_DNN_OPENCL: "OFF"
      OPENCV_DNN_TFLITE: "OFF"
      OPENCV_ENABLE_ALLOCATOR_STATS: "OFF"
      OPENCV_TRACE: "OFF"
      ENABLE_LTO: "ON"
      CMAKE_INTERPROCEDURAL_OPTIMIZATION: "ON"
      OPENCV_BIN_INSTALL_PATH: "bin"
      OPENCV_LIB_INSTALL_PATH: "lib"
      OPENCV_INCLUDE_INSTALL_PATH: "include"
      OPENCV_CONFIG_INSTALL_PATH: "lib/cmake/opencv4"
