sources:
  "1.10.0":
    url: "https://github.com/lz4/lz4/archive/refs/tags/v1.10.0.tar.gz"
    sha256: "537512904744b35e232912055ccf8ec66d768639ff3abe5788d90d792ec5f48b"
    archive_type: "tar.gz"
    strip_prefix: "lz4-1.10.0"
build:
  source_subdir: "build/cmake"
  cmake_options:
    BUILD_SHARED_LIBS: "ON"
    LZ4_BUILD_CLI: "OFF"
    LZ4_BUILD_LEGACY_LZ4C: "OFF"
