include_guard(GLOBAL)

include("${CMAKE_CURRENT_LIST_DIR}/BAASConanRuntime.cmake")

function(baas_request_dependencies)
    get_property(_requested GLOBAL PROPERTY BAAS_REQUESTED_DEPENDENCIES)
    set(_last_dependency "")
    set(_provider_dependency "")
    foreach(_arg IN LISTS ARGN)
        if(_arg STREQUAL "")
            continue()
        endif()

        if(_provider_dependency)
            set_property(GLOBAL PROPERTY "BAAS_REQUESTED_DEPENDENCY_PROVIDER_${_provider_dependency}" "${_arg}")
            set(_provider_dependency "")
            continue()
        endif()

        if(_arg STREQUAL "PROVIDER")
            if(_last_dependency STREQUAL "")
                message(FATAL_ERROR "baas_request_dependencies PROVIDER requires a dependency name before it")
            endif()
            set(_provider_dependency "${_last_dependency}")
            continue()
        endif()

        list(APPEND _requested "${_arg}")
        set(_last_dependency "${_arg}")
    endforeach()

    if(_provider_dependency)
        message(FATAL_ERROR "baas_request_dependencies missing provider value for dependency '${_provider_dependency}'")
    endif()
    if(_requested)
        list(REMOVE_DUPLICATES _requested)
    endif()
    set_property(GLOBAL PROPERTY BAAS_REQUESTED_DEPENDENCIES "${_requested}")
endfunction()

function(_baas_conan_generator_dir out_var)
    if(NOT DEFINED CMAKE_TOOLCHAIN_FILE OR CMAKE_TOOLCHAIN_FILE STREQUAL "")
        set(${out_var} "" PARENT_SCOPE)
        return()
    endif()

    get_filename_component(_toolchain_dir "${CMAKE_TOOLCHAIN_FILE}" DIRECTORY)
    if(EXISTS "${_toolchain_dir}/conan_toolchain.cmake")
        set(${out_var} "${_toolchain_dir}" PARENT_SCOPE)
        return()
    endif()
    set(${out_var} "" PARENT_SCOPE)
endfunction()

function(_baas_require_conan_generators)
    _baas_conan_generator_dir(_generator_dir)
    if(NOT _generator_dir)
        message(FATAL_ERROR
                "BAAS dependencies are provided by Conan. Run conan install before CMake configure.\n"
                "Example:\n"
                "  python deploy/conan/scripts/manage_recipes.py export\n"
                "  conan install deploy/conan -of build/conan/windows-msvc-release -pr:h=deploy/conan/profiles/windows-msvc-release -pr:h=deploy/conan/profiles/dependency-versions-default --build=missing --no-remote\n"
                "Then configure with -DCMAKE_TOOLCHAIN_FILE=build/conan/windows-msvc-release/generators/conan_toolchain.cmake")
    endif()
    list(PREPEND CMAKE_PREFIX_PATH "${_generator_dir}")
    set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}" PARENT_SCOPE)
endfunction()

function(_baas_find_requested_package dependency)
    if(dependency STREQUAL "opencv" OR dependency STREQUAL "opencv_dnn")
        find_package(baas-opencv CONFIG REQUIRED)
        if(dependency STREQUAL "opencv_dnn" AND NOT TARGET BAAS::OpenCVDnn)
            if(TARGET BAAS::OpenCV)
                add_library(BAAS::OpenCVDnn INTERFACE IMPORTED GLOBAL)
                target_link_libraries(BAAS::OpenCVDnn INTERFACE BAAS::OpenCV)
            endif()
        endif()
        if(dependency STREQUAL "opencv_dnn" AND NOT TARGET BAAS::OpenCVDnn)
            message(FATAL_ERROR "opencv_dnn requires conan install with -o \"&:use_opencv_dnn=True\"")
        endif()
    elseif(dependency STREQUAL "onnxruntime")
        find_package(baas-onnxruntime CONFIG REQUIRED)
        get_property(_provider GLOBAL PROPERTY "BAAS_REQUESTED_DEPENDENCY_PROVIDER_onnxruntime")
        if(_provider STREQUAL "cuda" AND NOT TARGET BAAS::ONNXRuntimeCUDAProvider)
            message(FATAL_ERROR "onnxruntime PROVIDER cuda requires conan install with -o \"&:onnxruntime_use_cuda=True\"")
        endif()
    elseif(dependency STREQUAL "ffmpeg")
        find_package(baas-ffmpeg CONFIG REQUIRED)
    elseif(dependency STREQUAL "lz4")
        find_package(baas-lz4 CONFIG REQUIRED)
    elseif(dependency STREQUAL "nlohmann_json")
        find_package(baas-nlohmann-json CONFIG REQUIRED)
    elseif(dependency STREQUAL "cpp_httplib")
        find_package(baas-cpp-httplib CONFIG REQUIRED)
    elseif(dependency STREQUAL "spdlog")
        find_package(baas-spdlog CONFIG REQUIRED)
    elseif(dependency STREQUAL "simdutf")
        find_package(baas-simdutf CONFIG REQUIRED)
    elseif(dependency STREQUAL "benchmark")
        find_package(baas-benchmark CONFIG REQUIRED)
    else()
        message(FATAL_ERROR "Unknown BAAS Conan dependency: ${dependency}")
    endif()
endfunction()

function(baas_load_requested_dependencies)
    get_property(_requested GLOBAL PROPERTY BAAS_REQUESTED_DEPENDENCIES)
    if(NOT _requested)
        return()
    endif()
    list(REMOVE_DUPLICATES _requested)

    _baas_require_conan_generators()
    foreach(_dependency IN LISTS _requested)
        _baas_find_requested_package("${_dependency}")
    endforeach()
endfunction()
